bundler/gems/spotlight-4a916cf7283c/config/routes.rb
Spotlight::Engine.routes.draw do
  devise_for :contact_email, class_name: 'Spotlight::ContactEmail', only: [:confirmations]

  concern :user_existable do
    collection do
      get :exists
    end
  end

  concern :user_invitable do
    collection do
      post :invite
    end
  end

  resource :site, only: [:edit, :update] do
    collection do
      get '/tags', to: 'sites#tags'
    end
  end

  get '/exhibits/edit', to: 'sites#edit_exhibits', as: 'edit_site_exhibits'
  get '/exhibits/new', to: 'exhibits#new', as: 'new_exhibit'
  resources :admin_users, only: [:index, :create, :destroy], concerns: [:user_existable, :user_invitable]

  resources :exhibits, path: '/', except: [:show] do
    member do
      get 'exhibit', to: 'exhibits#show', as: 'get'
      post 'import', to: 'exhibits#process_import'
      patch 'import', to: 'exhibits#process_import'
      post 'reindex', to: 'exhibits#reindex'
    end

    resources :attachments, only: :create
    resource :contact_form, path: 'contact', only: [:new, :create]
    resource :blacklight_configuration, only: [:update]

    resource :appearance, only: [:edit, :update]

    resource :metadata_configuration, only: [:show, :edit, :update]
    resource :search_configuration, only: [:show, :edit, :update]
    resource :view_configuration, only: [:show]

    resources :filters, only: [:create, :update]

    blacklight_for :catalog, only: [:export]

    resources :catalog, only: [:index, :show, :edit, :update] do
      collection do
        get 'admin'
        get 'autocomplete'
      end

      get 'facet/:id', to: 'catalog#facet', as: 'catalog_facet'

      put 'visiblity', to: 'catalog#make_public'
      delete 'visiblity', to: 'catalog#make_private'
    end

    get 'catalog/:id', to: 'catalog#show', as: 'solr_document'
    
    get 'annotation/:id/show', to: 'catalog#show_annotation', as: 'show_annotation'
    post 'annotation/:id/get', to: 'catalog#get_annotation'
    post 'annotation/:id/create', to: 'catalog#create_annotation'
    post 'annotation/:id/update', to: 'catalog#update_annotation'
    
    resources :solr_document, only: [:edit], to: 'catalog#edit'

    resources :custom_fields

    resource :dashboard, only: [:show] do
      get :analytics
    end

    resources :resources do
      collection do
        get :monitor
        post :reindex_all
      end
    end

    resources :resources_uploads, controller: 'resources/upload', path: 'upload_resources', only: [:create]

    resources :resources_csv_uploads, controller: 'resources/csv_upload', path: 'upload_csv', only: [:create] do
      collection do
        get :template
      end
    end

    resources :searches do
      collection do
        patch :update_all
      end
      member do
        get :autocomplete
      end
    end
    resources :browse, only: [:index, :show]
    resources :tags, only: [:index, :destroy]

    resources :contacts, only: [:edit, :update, :destroy]
    resources :about_pages, path: 'about' do
      collection do
        patch 'contacts' => 'about_pages#update_contacts'
        resources :contacts, only: [:new, :create]
        patch :update_all
      end
    end
    resources :feature_pages, path: 'feature' do
      collection do
        patch :update_all
      end
    end
    resource :home_page, path: 'home', controller: 'home_pages'
    post '/pages/:id/preview' => 'pages#preview', as: :preview_block

    resources :lock, only: [:destroy]

    resources :roles, path: 'users', only: [:index, :create, :destroy], concerns: [:user_existable, :user_invitable] do
      collection do
        patch :update_all
      end
    end
    post 'solr/update' => 'solr#update'
  end

  get '/:exhibit_id' => 'home_pages#show', as: :exhibit_root
  post 'versions/:id/revert' => 'versions#revert', as: :revert_version
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/ar_light.rb
module Spotlight
  ##
  # Stub ActiveRecord methods to allow non-ActiveRecord::Base objects to
  # participate in e.g. associations
  module ArLight
    extend ActiveSupport::Concern
    include ActiveRecord::ModelSchema
    include ActiveRecord::Inheritance
    include ActiveRecord::Associations
    include ActiveRecord::Reflection
    include ActiveModel::Dirty

    ##
    # Mock activerecord class-level methods
    module ClassMethods
      def base_class
        self
      end

      # required for Rails >= 4.0.4
      def subclass_from_attributes?(_)
        false
      end

      def generated_feature_methods
        @generated_feature_methods ||= begin
          mod = const_set(:GeneratedFeatureMethods, Module.new)
          include mod
          mod
        end
      end

      def before_destroy(*_args)
      end

      def pluralize_table_names
        true
      end

      def add_autosave_association_callbacks(_arg)
      end

      # needed for Rails 4.1 + act_as_taggable
      def dangerous_attribute_method?(*_args)
        false
      end

      # needed for Rails 4.1 + act_as_taggable
      def generated_association_methods
        @generated_association_methods ||= begin
          mod = const_set(:GeneratedAssociationMethods, Module.new)
          include mod
          mod
        end
      end

      def validators_on(*_)
        []
      end

      def default_scopes
        []
      end
    end

    def initialize(source_doc = {}, solr_response = nil)
      @association_cache = {}
      super
    end

    # Returns true if +comparison_object+ is the same exact object, or +comparison_object+
    # is of the same type and +self+ has an ID and it is equal to +comparison_object.id+.
    #
    # Note that new records are different from any other record by definition, unless the
    # other record is the receiver itself. Besides, if you fetch existing records with
    # +select+ and leave the ID out, you're on your own, this predicate will return false.
    #
    # Note also that destroying a record preserves its ID in the model instance, so deleted
    # models are still comparable.
    def ==(other)
      super ||
        (other.instance_of?(self.class) &&
          id &&
          other.id == id)
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/blacklight_configuration_defaults.rb
module Spotlight
  ##
  # Helpers to provide default blacklight configuration values
  module BlacklightConfigurationDefaults
    extend ActiveSupport::Concern

    included do
      before_create :setup_defaults
      attr_accessor :skip_default_configuration
    end

    protected

    def setup_defaults
      return if skip_default_configuration

      default_search_fields
      default_sort_fields
      default_view_types
      set_default_per_page
    end

    def default_search_fields
      return true unless search_fields.empty?

      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      default_fields = Spotlight::Engine.blacklight_config.search_fields
      self.search_fields = default_fields.each_with_object({}) do |(k, _v), obj|
        obj[k] = { enabled: true }
      end
    end

    def default_sort_fields
      return true unless sort_fields.empty?

      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      default_fields = Spotlight::Engine.blacklight_config.sort_fields
      self.sort_fields = default_fields.each_with_object({}) do |(k, _v), obj|
        obj[k] = { enabled: true }
      end
    end

    def default_view_types
      return true unless document_index_view_types.empty?

      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      self.document_index_view_types = Spotlight::Engine.blacklight_config.view.keys.map(&:to_s)
    end

    def set_default_per_page
      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      self.default_per_page ||= Spotlight::Engine.blacklight_config.per_page.first
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/default_thumbnailable.rb
module Spotlight
  ###
  #  Simple concern to mixin to classes that
  #  fetches a default thumbnail after creation
  #  Classes that mixin this module should implement
  #  a set_default_thumbnail method themselves
  ###
  module DefaultThumbnailable
    extend ActiveSupport::Concern

    included do
      after_create(:fetch_default_thumb_later) if respond_to?(:after_create)
    end

    private

    def fetch_default_thumb_later
      DefaultThumbnailJob.perform_later(self)
    end

    def set_default_thumbnail
      fail NotImplementedError
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/exhibit_analytics.rb
module Spotlight
  ##
  # Exhibit mixin to provide analytics data
  module ExhibitAnalytics
    def analytics(start_date = 1.month, path = nil)
      return OpenStruct.new unless analytics_provider && analytics_provider.enabled?
      @analytics ||= {}
      @analytics[start_date] ||= begin
        analytics_provider.exhibit_data(path || self, start_date: start_date.ago)
      end
    end

    def page_analytics(start_date = 1.month, path = nil)
      return [] unless analytics_provider && analytics_provider.enabled?

      @page_analytics ||= {}
      @page_analytics[start_date] ||= begin
        analytics_provider.page_data(path || self, start_date: start_date.ago)
      end
    end

    private

    def analytics_provider
      Spotlight::Engine.config.analytics_provider
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/exhibit_defaults.rb
module Spotlight
  # Mixin for adding default configuration to exhibits
  module ExhibitDefaults
    extend ActiveSupport::Concern

    included do
      before_create :build_home_page
      before_create :add_site_reference
      after_create :initialize_config
      after_create :initialize_browse
      after_create :initialize_main_navigation
      after_create :initialize_filter
    end

    protected

    def initialize_filter
	  p "\n\n 4a916 exhibit_defaults.rb here 18\n\n"
      return unless Spotlight::Engine.config.filter_resources_by_exhibit
	  p "\n\n 4a916 here  exhibit_defaults.rb 20\n\n"
      filters.create field: default_filter_field, value: default_filter_value
    end

    def initialize_config
      self.blacklight_configuration ||= Spotlight::BlacklightConfiguration.create!
    end

    def initialize_browse
      return unless searches.blank?

      searches.create title: 'All Exhibit Items',
                      long_description: 'All items in this exhibit.'
    end

    def initialize_main_navigation
      default_main_navigations.each_with_index do |nav_type, weight|
        main_navigations.create nav_type: nav_type, weight: weight
      end
    end

    def add_site_reference
      self.site ||= Spotlight::Site.instance
    end

    def default_filter_field
      "#{Spotlight::Engine.config.solr_fields.prefix}spotlight_exhibit_slug_#{slug}#{Spotlight::Engine.config.solr_fields.boolean_suffix}"
    end

    # Return a string to work around any ActiveRecord type-casting
    def default_filter_value
      'true'
    end

    private

    def default_main_navigations
      Spotlight::Engine.config.exhibit_main_navigation.dup
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/exhibit_documents.rb
module Spotlight
  # Mixin for retrieving solr documents for a specific exhibit
  module ExhibitDocuments
    ##
    # Retrieve all the solr documents associated with this exhibit, appropriately
    # filtered by the exhibit-specific solr field.
    #
    # @return [Enumerable<SolrDocument>]
    def solr_documents
      return to_enum(:solr_documents) unless block_given?

      start = 0
      search_params = exhibit_search_builder.merge(q: '*:*', fl: '*')

      response = repository.search(search_params.start(start).to_h)

      while response.documents.present?
        response.documents.each { |x| yield x }
        start += response.documents.length
        response = repository.search(search_params.start(start).to_h)
      end
    end

    private

    def exhibit_search_builder
      blacklight_config.search_builder_class.new(true, exhibit_search_builder_context).except(:apply_permissive_visibility_filter)
    end

    def exhibit_search_builder_context
      OpenStruct.new(blacklight_config: blacklight_config, current_exhibit: self)
    end

    def repository
      @repository ||= Blacklight.repository_class.new(blacklight_config) if Blacklight.respond_to? :repository_class
      @repository ||= Blacklight::Solr::Repository.new(blacklight_config)
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/image_derivatives.rb
module Spotlight
  ###
  # Include Spotlight::ImageDerivatives in a class or module to get
  # the derivative configurations in #spotlight_image_derivatives.
  # A new derivative could theoretically be added by putting the
  # following in an initializer.
  # Spotlight::ImageDerivatives.spotlight_image_derivatives << {
  #   version: :my_version,
  #   field: :my_field,
  #   lambda: lambda {|_|
  #     version :my_version do
  #       process :resize_to_fill => [30,30]
  #     end
  #   }
  # }
  #
  # This will then create that new CarrierWave version in any class that extends this module
  # and calls the apply_spotlight_image_derivative_versions class method described below.
  module ImageDerivatives
    mattr_accessor :spotlight_image_derivatives

    # Extend Spotlight::ImageDerivatives in a CarrierWave uploader
    # then you can call this as a class method and all of the
    # configured versions will be available
    def apply_spotlight_image_derivative_versions
      spotlight_image_derivatives.each do |version_config|
        if (c = version_config[:lambda]).present?
          class_eval(&c)
        end
      end
    end

    # Set default derivative configurations
    self.spotlight_image_derivatives ||= [
      {
        field: Spotlight::Engine.config.try(:full_image_field),
        lambda: lambda do|_|
            process convert: [:jpeg]
        end
      },
      {
        version: :thumb,
        field: Spotlight::Engine.config.try(:thumbnail_field),
        lambda: lambda do|_|
          version :thumb do
            process resize_to_fit: [400, 400]
            process convert: [:jpeg]
          end
        end
      },
      {
        version: :square,
        field: Spotlight::Engine.config.try(:square_image_field),
        lambda: lambda do|_|
          version :square do
            process resize_to_fill: [100, 100]
            process convert: [:jpeg]
          end
        end
      }
    ].reject { |v| v[:field].blank? }
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/resources/open_graph.rb
module Spotlight
  module Resources
    ##
    # OpenGraph metadata harvester
    module OpenGraph
      extend ActiveSupport::Concern
      include Spotlight::Resources::Web

      def opengraph
        @opengraph ||= begin
          page = {}

          body.css('meta').select { |m| m.attribute('property') }.each do |m|
            page[m.attribute('property').to_s] = m.attribute('content').to_s
          end

          page
        end
      end

      def opengraph_properties
        Hash[opengraph.map do |k, v|
          ["#{k.parameterize('_')}_tesim", v]
        end]
      end

      def to_solr
        super.merge(opengraph_properties)
      end
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/resources/web.rb
require 'nokogiri'

module Spotlight
  module Resources
    ##
    # Generic web resource harvester base module
    module Web
      extend ActiveSupport::Concern

      included do
        before_create do
          harvest!
        end
      end

      def harvest!
        response = Spotlight::Resources::Web.fetch url
        data[:headers] = response.headers
        data[:body] = response.body
      end

      def body
        harvest! if data[:body].blank?

        @body ||= Nokogiri::HTML.parse data[:body]
      end

      def self.fetch(url)
        Faraday.new(url) do |b|
          b.use FaradayMiddleware::FollowRedirects
          b.adapter :net_http
        end.get
      end
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/concerns/spotlight/solr_document/active_model_concern.rb
module Spotlight
  module SolrDocument
    ##
    # ActiveModel stubs to make {::SolrDocument}s work as activemodel objects
    module ActiveModelConcern
      extend ActiveSupport::Concern

      included do
        include Spotlight::ArLight
        extend ActiveModel::Callbacks
        define_model_callbacks :save
      end

      def save
        run_callbacks :save do
          # no-op
        end
      end

      def to_key
        [id]
      end

      def persisted?
        true
      end

      def destroyed?
        false
      end

      def new_record?
        !persisted?
      end
    end
  end
end

bundler/gems/spotlight-4a916cf7283c/app/models/spotlight/about_page.rb
module Spotlight
  ##
  # About pages
  class AboutPage < Spotlight::Page
    extend FriendlyId
    friendly_id :title, use: [:slugged, :scoped, :finders, :history], scope: :exhibit
  end
end

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_confirmation_status.html.erb
            <div class="col-md-4 confirmation-status <%= 'not-validated' unless contact_email.confirmed? or contact_email.recently_sent? %>">
              <% if contact_email.confirmed? %>
                <span class="confirmed"><span class="glyphicon glyphicon-ok-sign"></span> <%= t('.confirmed') %></span>
              <% elsif contact_email.recently_sent? %>
                <span class="confirmed"><span class="glyphicon glyphicon-ok-sign"></span> <%= t('.confirmation_sent') %></span>
              <% else %>
                <span class="unconfirmed"><span class="glyphicon glyphicon-exclamation-sign"></span> <%= t('.not_validated') %></span> <%= link_to t('.resend'), contact_email_confirmation_path(contact_email: {email: contact_email.email}),  method: :post %>
              <% end %>
            </div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_delete.html.erb
<div role="tabpanel" class="tab-pane" id="delete">
  <div class="callout callout-danger row">
    <h4><%= t(:".heading") %></h4>
    <p class='col-md-9'><%= t(:".warning_html", export_link: link_to(t(:'spotlight.exhibits.export.download'), spotlight.import_exhibit_path(current_exhibit))) %></p>
    <div class='col-md-3'>
      <%= delete_link current_exhibit, class: 'btn btn-default' %>
    </div>
  </div>
</div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_exhibit_card.html.erb
<div class="col-xs-12 col-sm-4 exhibit-card">
  <div class="flipper">
    <div class="card-front card-face">
      <%= render 'exhibit_card_front', exhibit: exhibit %>
    </div>
    <div class="card-back card-face">
      <%= render 'exhibit_card_back', exhibit: exhibit %>
    </div>
  </div>
</div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_exhibit_card_back.html.erb
<h2 class="card-title">
  <%= exhibit.title %>
</h2>

<p class="subtitle">
  <%= exhibit.subtitle %>
</p>

<% if exhibit.description %>
  <p class="description">
    <%= exhibit.description.truncate(168, omission: "") %>
    <% if exhibit.description.length > 168 %>
      <%= content_tag(:span,"&hellip;".html_safe, class: "visible-sm visible-md") %>
      <span class="hidden-sm hidden-md">
        <%= exhibit.description.slice(168, exhibit.description.length) %>
      </span>
    <% end %>
  </p>
<% end %>

<div class="visit-exhibit center-btn">
  <%= link_to t(:'.visit_exhibit'), exhibit, class: "btn btn-primary", role: "button" %>
</div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_exhibit_card_front.html.erb
<% if exhibit.thumbnail.present? %>
  <%= image_tag(exhibit.thumbnail.image.square.url) %>
<% else %>
  <%= image_tag 'spotlight/default_thumbnail.jpg', class: 'default-thumbnail' %>
<% end %>

<% unless exhibit.published? %>
  <div class="label label-warning unpublished"><%= t('.unpublished') %></div>
<% end %>

<h2 class="card-title"><%= exhibit.title %></h2>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_exhibits.html.erb
<% exhibits.each_slice(3).each do |row| %>
  <div class="row"><!-- start main content row -->
    <%= render collection: row, partial: 'exhibit_card', as: 'exhibit' %>
  </div>
<% end %>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_export.html.erb
<div role="tabpanel" class="tab-pane" id="export">        
  <div class="row col-md-12">
    <p class="instructions"><%= t :'.instructions' %></p>
    <div class="primary-actions">
      <%= link_to t(:'.download'), get_exhibit_path(current_exhibit, format: 'json'), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_form.html.erb
<%= bootstrap_form_for @exhibit, url: ((spotlight.exhibit_path(@exhibit) if @exhibit.persisted?) || spotlight.exhibits_path), layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-10', html: {class: "row"} do |f| %>
<div class="row col-md-12">
  <%= f.text_field :title %>
  <%= f.text_field :subtitle %>
  <%= f.text_area :description %>
  <%= f.text_field :tag_list, value: f.object.tag_list.to_s %>
  <%= f.form_group(:contact_emails, label: { text: nil, class: nil }, help: nil) do %>
  <%= f.fields_for :contact_emails do |contact| %>
  <%= render partial: 'contact', locals: {contact: contact} %>
  <% end %>
  <p class="help-block"><%= t(:'.fields.contact_emails.help_block') %></p>
  <% end %>
  <%= f.form_group :published, label: { text: nil, class: nil }, help: nil do %>
  <%= f.check_box :published, label: "" %>
  <p class="help-block"><%= t(:'.fields.published.help_block') %></p>
  <% end %>
  
  <div class="form-actions">
    
    <div class="primary-actions">
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<% end %>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_import.html.erb
<div role="tabpanel" class="tab-pane" id="import">
  <%= bootstrap_form_for [:import, current_exhibit], html: { class: 'clearfix', multipart: true } do |f| %>
    <div class="row col-md-12">
      <p class="instructions"><%= t :'.instructions' %></p>
      <div class="form-group">
        <%= file_field_tag :file, class: 'form-control' %>
      </div>
      <div class="form-actions">
        <div class="primary-actions">
          <%= f.submit t(:'.button'), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_new_exhibit_form.html.erb
<%= bootstrap_form_for @exhibit, url: ((spotlight.exhibit_path(@exhibit) if @exhibit.persisted?) || spotlight.exhibits_path), layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-10', html: {class: "row"} do |f| %>
<div class="row col-md-12">
  <%= f.text_field :title, label: t(:'.fields.title.label'), help: t(:'.fields.title.help_block') %>
  <%= f.text_field :slug, label: t(:'.fields.slug.label'), help: t(:'.fields.slug.help_block') %>
  <%= f.text_field :tag_list %>

  <%= render 'initial_resources_form', locals: { f: f } %>

  <div class="form-actions">
    <div class="primary-actions">
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<% end %>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/_tags.html.erb
<% if tags.any? %>
<div class="row">
  <ul class="nav nav-pills col-md-10 col-md-offset-1 tags">
    <li class="<%= 'active' if params[:tag].blank? %>"><%= link_to t('.all'), exhibits_path %></li>

    <% tags.sort_by(&:name).each do |tag| %>
      <li class="<%= 'active' if params[:tag] == tag.name %>"><%= link_to tag.name, exhibits_path(tag: tag.name) %></li>
    <% end %>
  </ul>
</div>
<% end %>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/edit.html.erb
<%= render 'spotlight/shared/exhibit_sidebar' %>
<div id="content" class="col-md-9 exhibit-admin">
  <%= configuration_page_title %>
  <div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#basic" aria-controls="basic" role="tab" data-toggle="tab"><%= t(:'.basic_settings.heading') %></a>
      </li>
      <% if can? :edit, current_exhibit.filters.first_or_initialize %>
        <li role="presentation">
          <a href="#filter" aria-controls="filter" role="tab" data-toggle="tab"><%= t(:'spotlight.exhibits.filter.heading') %></a>
        </li>
      <% end %>
      <% if can? :import, current_exhibit %>
        <li role="presentation">
          <a href="#import" aria-controls="import" role="tab" data-toggle="tab"><%= t(:'spotlight.exhibits.import.heading') %></a>
        </li>
      <% end %>
      <% if can? :export, current_exhibit %>
        <li role="presentation">
          <a href="#export" aria-controls="export" role="tab" data-toggle="tab"><%= t(:'spotlight.exhibits.export.heading') %></a>
        </li>
      <% end %>
      <% if can? :destroy, current_exhibit %>
        <li role="presentation">
          <a href="#delete" aria-controls="delete" role="tab" data-toggle="tab"><%= t(:'spotlight.exhibits.delete.heading') %></a>
        </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="basic">
        <%= render 'form' %>
      </div>
      <%= render 'spotlight/filters/form' if can? :edit, current_exhibit.filters.first_or_initialize %>
      <%= render 'import' if can? :import, current_exhibit %>
      <%= render 'export' if can? :export, current_exhibit %>
      <%= render 'delete' if can? :destroy, current_exhibit %>
    </div>
  </div>
</div>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/index.html.erb
<div class="col-md-9">
  <% if (current_user && current_user.exhibits.any?) || can?(:manage, Spotlight::Exhibit) %>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#published" aria-controls="published" role="tab" data-toggle="tab"><%= t('.published') %></a></li>
      <% if can?(:manage, Spotlight::Exhibit) && @exhibits.unpublished.accessible_by(current_ability).any? %>
        <li role="presentation"><a href="#unpublished" aria-controls="unpublished" role="tab" data-toggle="tab"><%= t('.unpublished') %></a></li>
      <% end %>
      <% if current_user && current_user.exhibits.any? %>
        <li role="presentation"><a href="#user" aria-controls="user" role="tab" data-toggle="tab"><%= t('.user') %></a></li>
      <% end %>
    </ul>
  <% end %>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="published">
      <% if @exhibits.published.none? %>
        <%= render 'missing_exhibits' %>
      <% else %>
        <%= render 'tags', tags: @exhibits.published.all_tags %>
        <%= render 'exhibits', exhibits: @published_exhibits %>

        <% if @published_exhibits.total_count > @published_exhibits.size %>
          <nav>
            <ul class="pager">
              <li><%= link_to_previous_page @published_exhibits, t('views.pagination.previous').html_safe %></li>
              <li><%= link_to_next_page @published_exhibits, t('views.pagination.next').html_safe %></li>
            </ul>
          </nav>
        <% end %>
      <% end %>

    </div>

    <% if @exhibits.unpublished.accessible_by(current_ability).any? %>
      <div role="tabpanel" class="tab-pane" id="unpublished">
        <%= render 'exhibits', exhibits: @exhibits.unpublished.accessible_by(current_ability) %>
      </div>
    <% end %>

    <% if current_user && current_user.exhibits.any? %>
      <div role="tabpanel" class="tab-pane" id="user">
        <%= render 'exhibits', exhibits: current_user.exhibits %>
      </div>
    <% end %>
  </div>
</div>

<aside class="col-md-3">
  <%= render "shared/site_sidebar" %>
</aside>

bundler/gems/spotlight-4a916cf7283c/app/views/spotlight/exhibits/new.html.erb
<div id="content" class="col-md-9 exhibit-admin">
<%= configuration_page_title %>
<%= render 'new_exhibit_form' %>
</div>